add_newline = false
# A minimal left prompt
format = """$directory$character"""
palette = "catppuccin_latte"
# move the rest of the prompt to the right
right_format = """$all"""
command_timeout = 1000

[directory.substitutions]
"~/Developer/nunocgoncalves" = "dev"
"~/Developer/Iterabase-x-AI-Square" = "iterabase-ai"
"~/Developer/worktrees" = "wt"
"~/Documents/2nd-brain" = "brain"

[git_branch]
format =  '[$symbol$branch(:$remote_branch)]($style)'

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
style = 'bold blue'
symbol = " "

[golang]
format = '[ ](bold cyan)'

[kubernetes]
symbol = '☸ '
detect_files = ['Dockerfile']
format = '[$symbol$context( \($namespace\))]($style) '

[docker_context]
disabled = true

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"
